PR_TITLE_REGEX: /(Revert.+)|(Merge.+)|(Hotfix.+)|(Auto.+)|(\[)?([A-Z0-9]+)-(\d+)(\])?(.+)/i
COMMIT_MESSAGE_REGEX: /(Revert.+)|(Merge.+)|(Hotfix.+)|(Auto.+)|(\[)?([A-Z0-9]+)-(\d+)(\])?(.+)/i

OUTPUT_TITLE_FAIL: Message validation failed!
OUTPUT_TITLE_SUCCESS: Message validation passed!
VALID_COMMIT_MESSAGE: Commit messages are valid
INVALID_COMMIT_MESSAGE: Commit messages are invalid
SINGLE_OTHER_INVALID_MESSAGE: other message is invalid
MULTIPLE_OTHER_INVALID_MESSAGE: other messages are invalid
VALID_PULL_REQUEST_MESSAGE: Pull request title is valid
INVALID_PULL_REQUEST_MESSAGE: Pull request title is invalid
